/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HisabRouteImport } from './routes/hisab'
import { Route as HisabIndexRouteImport } from './routes/hisab.index'
import { Route as HisabActivityRouteImport } from './routes/hisab.activity'
import { Route as HisabFilesRouteImport } from './routes/hisab.files'
import { Route as HisabHelpRouteImport } from './routes/hisab.help'
import { Route as HisabListRouteImport } from './routes/hisab.list'
import { Route as HisabLoginRouteImport } from './routes/hisab.login'
import { Route as HisabMoreRouteImport } from './routes/hisab.more'
import { Route as HisabNewRouteImport } from './routes/hisab.new'
import { Route as HisabPartiesRouteImport } from './routes/hisab.parties'
import { Route as HisabProductsRouteImport } from './routes/hisab.products'
import { Route as HisabQuotationsRouteImport } from './routes/hisab.quotations'
import { Route as HisabReportsRouteImport } from './routes/hisab.reports'
import { Route as HisabStockRouteImport } from './routes/hisab.stock'
import { Route as ApiHisabScanRouteImport } from './routes/api/hisab/scan'
import { Route as HisabInvoiceIdRouteImport } from './routes/hisab.invoice.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabRoute = HisabRouteImport.update({
  id: '/hisab',
  path: '/hisab',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabIndexRoute = HisabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HisabRoute,
} as any)
const HisabActivityRoute = HisabActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => HisabRoute,
} as any)
const HisabFilesRoute = HisabFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => HisabRoute,
} as any)
const HisabHelpRoute = HisabHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HisabRoute,
} as any)
const HisabListRoute = HisabListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => HisabRoute,
} as any)
const HisabLoginRoute = HisabLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HisabRoute,
} as any)
const HisabMoreRoute = HisabMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => HisabRoute,
} as any)
const HisabNewRoute = HisabNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HisabRoute,
} as any)
const HisabPartiesRoute = HisabPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => HisabRoute,
} as any)
const HisabProductsRoute = HisabProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => HisabRoute,
} as any)
const HisabQuotationsRoute = HisabQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => HisabRoute,
} as any)
const HisabReportsRoute = HisabReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HisabRoute,
} as any)
const HisabStockRoute = HisabStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => HisabRoute,
} as any)
const ApiHisabScanRoute = ApiHisabScanRouteImport.update({
  id: '/api/hisab/scan',
  path: '/api/hisab/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const HisabInvoiceIdRoute = HisabInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => HisabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hisab': typeof HisabRouteWithChildren
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/login': typeof HisabLoginRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/quotations': typeof HisabQuotationsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/': typeof HisabIndexRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/login': typeof HisabLoginRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/quotations': typeof HisabQuotationsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab': typeof HisabIndexRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hisab': typeof HisabRouteWithChildren
  '/hisab/activity': typeof HisabActivityRoute
  '/hisab/files': typeof HisabFilesRoute
  '/hisab/help': typeof HisabHelpRoute
  '/hisab/list': typeof HisabListRoute
  '/hisab/login': typeof HisabLoginRoute
  '/hisab/more': typeof HisabMoreRoute
  '/hisab/new': typeof HisabNewRoute
  '/hisab/parties': typeof HisabPartiesRoute
  '/hisab/products': typeof HisabProductsRoute
  '/hisab/quotations': typeof HisabQuotationsRoute
  '/hisab/reports': typeof HisabReportsRoute
  '/hisab/stock': typeof HisabStockRoute
  '/hisab/': typeof HisabIndexRoute
  '/api/hisab/scan': typeof ApiHisabScanRoute
  '/hisab/invoice/$id': typeof HisabInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hisab'
    | '/hisab/activity'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/login'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/quotations'
    | '/hisab/reports'
    | '/hisab/stock'
    | '/hisab/'
    | '/api/hisab/scan'
    | '/hisab/invoice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hisab/activity'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/login'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/quotations'
    | '/hisab/reports'
    | '/hisab/stock'
    | '/hisab'
    | '/api/hisab/scan'
    | '/hisab/invoice/$id'
  id:
    | '__root__'
    | '/'
    | '/hisab'
    | '/hisab/activity'
    | '/hisab/files'
    | '/hisab/help'
    | '/hisab/list'
    | '/hisab/login'
    | '/hisab/more'
    | '/hisab/new'
    | '/hisab/parties'
    | '/hisab/products'
    | '/hisab/quotations'
    | '/hisab/reports'
    | '/hisab/stock'
    | '/hisab/'
    | '/api/hisab/scan'
    | '/hisab/invoice/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HisabRoute: typeof HisabRouteWithChildren
  ApiHisabScanRoute: typeof ApiHisabScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab': {
      id: '/hisab'
      path: '/hisab'
      fullPath: '/hisab'
      preLoaderRoute: typeof HisabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab/': {
      id: '/hisab/'
      path: '/'
      fullPath: '/hisab/'
      preLoaderRoute: typeof HisabIndexRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/activity': {
      id: '/hisab/activity'
      path: '/activity'
      fullPath: '/hisab/activity'
      preLoaderRoute: typeof HisabActivityRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/files': {
      id: '/hisab/files'
      path: '/files'
      fullPath: '/hisab/files'
      preLoaderRoute: typeof HisabFilesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/help': {
      id: '/hisab/help'
      path: '/help'
      fullPath: '/hisab/help'
      preLoaderRoute: typeof HisabHelpRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/list': {
      id: '/hisab/list'
      path: '/list'
      fullPath: '/hisab/list'
      preLoaderRoute: typeof HisabListRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/login': {
      id: '/hisab/login'
      path: '/login'
      fullPath: '/hisab/login'
      preLoaderRoute: typeof HisabLoginRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/more': {
      id: '/hisab/more'
      path: '/more'
      fullPath: '/hisab/more'
      preLoaderRoute: typeof HisabMoreRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/new': {
      id: '/hisab/new'
      path: '/new'
      fullPath: '/hisab/new'
      preLoaderRoute: typeof HisabNewRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/parties': {
      id: '/hisab/parties'
      path: '/parties'
      fullPath: '/hisab/parties'
      preLoaderRoute: typeof HisabPartiesRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/products': {
      id: '/hisab/products'
      path: '/products'
      fullPath: '/hisab/products'
      preLoaderRoute: typeof HisabProductsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/quotations': {
      id: '/hisab/quotations'
      path: '/quotations'
      fullPath: '/hisab/quotations'
      preLoaderRoute: typeof HisabQuotationsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/reports': {
      id: '/hisab/reports'
      path: '/reports'
      fullPath: '/hisab/reports'
      preLoaderRoute: typeof HisabReportsRouteImport
      parentRoute: typeof HisabRoute
    }
    '/hisab/stock': {
      id: '/hisab/stock'
      path: '/stock'
      fullPath: '/hisab/stock'
      preLoaderRoute: typeof HisabStockRouteImport
      parentRoute: typeof HisabRoute
    }
    '/api/hisab/scan': {
      id: '/api/hisab/scan'
      path: '/api/hisab/scan'
      fullPath: '/api/hisab/scan'
      preLoaderRoute: typeof ApiHisabScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisab/invoice/$id': {
      id: '/hisab/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/hisab/invoice/$id'
      preLoaderRoute: typeof HisabInvoiceIdRouteImport
      parentRoute: typeof HisabRoute
    }
  }
}

interface HisabRouteChildren {
  HisabActivityRoute: typeof HisabActivityRoute
  HisabFilesRoute: typeof HisabFilesRoute
  HisabHelpRoute: typeof HisabHelpRoute
  HisabListRoute: typeof HisabListRoute
  HisabLoginRoute: typeof HisabLoginRoute
  HisabMoreRoute: typeof HisabMoreRoute
  HisabNewRoute: typeof HisabNewRoute
  HisabPartiesRoute: typeof HisabPartiesRoute
  HisabProductsRoute: typeof HisabProductsRoute
  HisabQuotationsRoute: typeof HisabQuotationsRoute
  HisabReportsRoute: typeof HisabReportsRoute
  HisabStockRoute: typeof HisabStockRoute
  HisabIndexRoute: typeof HisabIndexRoute
  HisabInvoiceIdRoute: typeof HisabInvoiceIdRoute
}

const HisabRouteChildren: HisabRouteChildren = {
  HisabActivityRoute: HisabActivityRoute,
  HisabFilesRoute: HisabFilesRoute,
  HisabHelpRoute: HisabHelpRoute,
  HisabListRoute: HisabListRoute,
  HisabLoginRoute: HisabLoginRoute,
  HisabMoreRoute: HisabMoreRoute,
  HisabNewRoute: HisabNewRoute,
  HisabPartiesRoute: HisabPartiesRoute,
  HisabProductsRoute: HisabProductsRoute,
  HisabQuotationsRoute: HisabQuotationsRoute,
  HisabReportsRoute: HisabReportsRoute,
  HisabStockRoute: HisabStockRoute,
  HisabIndexRoute: HisabIndexRoute,
  HisabInvoiceIdRoute: HisabInvoiceIdRoute,
}

const HisabRouteWithChildren = HisabRoute._addFileChildren(HisabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HisabRoute: HisabRouteWithChildren,
  ApiHisabScanRoute: ApiHisabScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
